name: Lint Clojure
on: [pull_request]
jobs:
  clj-kondo:
    name: runner / clj-kondo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: clj-kondo
        uses: nnichols/clojure-lint-action@v2
        with:
          github_token: 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
          reporter: github-pr-review