(ns cral.alfresco.model.alfresco.cm)

(def cm-uri "http://www.alfresco.org/model/content/1.0")
(def cm-prefix "cm")
(def rn-uri "http://www.alfresco.org/model/rendition/1.0")
(def rn-prefix "rn")
(def exif-uri "http://www.alfresco.org/model/exif/1.0")
(def exif-prefix "exif")
(def audio-uri "http://www.alfresco.org/model/audio/1.0")
(def audio-prefix "audio")
(def webdav-uri "http://www.alfresco.org/model/webdav/1.0")
(def webdav-prefix "webdav")
(def type-cmobject-localname "cmobject")
(def type-cmobject (format "%s:%s" cm-prefix type-cmobject-localname))
(def type-folder-localname "folder")
(def type-folder (format "%s:%s" cm-prefix type-folder-localname))
(def type-content-localname "content")
(def type-content (format "%s:%s" cm-prefix type-content-localname))
(def type-dictionary-model-localname "dictionaryModel")
(def type-dictionary-model (format "%s:%s" cm-prefix type-dictionary-model-localname))
(def type-link-localname "link")
(def type-link (format "%s:%s" cm-prefix type-link-localname))
(def type-savedquery-localname "savedquery")
(def type-savedquery (format "%s:%s" cm-prefix type-savedquery-localname))
(def type-systemfolder-localname "systemfolder")
(def type-systemfolder (format "%s:%s" cm-prefix type-systemfolder-localname))
(def type-authority-localname "authority")
(def type-authority (format "%s:%s" cm-prefix type-authority-localname))
(def type-person-localname "person")
(def type-person (format "%s:%s" cm-prefix type-person-localname))
(def type-authority-container-localname "authorityContainer")
(def type-authority-container (format "%s:%s" cm-prefix type-authority-container-localname))
(def type-zone-localname "zone")
(def type-zone (format "%s:%s" cm-prefix type-zone-localname))
(def type-category_root-localname "category_root")
(def type-category_root (format "%s:%s" cm-prefix type-category_root-localname))
(def type-category-localname "category")
(def type-category (format "%s:%s" cm-prefix type-category-localname))
(def type-ml-root-localname "mlRoot")
(def type-ml-root (format "%s:%s" cm-prefix type-ml-root-localname))
(def type-ml-container-localname "mlContainer")
(def type-ml-container (format "%s:%s" cm-prefix type-ml-container-localname))
(def type-rating-localname "rating")
(def type-rating (format "%s:%s" cm-prefix type-rating-localname))
(def type-failed-thumbnail-localname "failedThumbnail")
(def type-failed-thumbnail (format "%s:%s" cm-prefix type-failed-thumbnail-localname))
(def type-thumbnail-localname "thumbnail")
(def type-thumbnail (format "%s:%s" cm-prefix type-thumbnail-localname))
(def asp-titled-localname "titled")
(def asp-titled (format "%s:%s" cm-prefix asp-titled-localname))
(def asp-auditable-localname "auditable")
(def asp-auditable (format "%s:%s" cm-prefix asp-auditable-localname))
(def asp-person-disabled-localname "personDisabled")
(def asp-person-disabled (format "%s:%s" cm-prefix asp-person-disabled-localname))
(def asp-annullable-localname "annullable")
(def asp-annullable (format "%s:%s" cm-prefix asp-annullable-localname))
(def asp-transformable-localname "transformable")
(def asp-transformable (format "%s:%s" cm-prefix asp-transformable-localname))
(def asp-templatable-localname "templatable")
(def asp-templatable (format "%s:%s" cm-prefix asp-templatable-localname))
(def asp-webscriptable-localname "webscriptable")
(def asp-webscriptable (format "%s:%s" cm-prefix asp-webscriptable-localname))
(def asp-projectsummary-localname "projectsummary")
(def asp-projectsummary (format "%s:%s" cm-prefix asp-projectsummary-localname))
(def asp-complianceable-localname "complianceable")
(def asp-complianceable (format "%s:%s" cm-prefix asp-complianceable-localname))
(def asp-ownable-localname "ownable")
(def asp-ownable (format "%s:%s" cm-prefix asp-ownable-localname))
(def asp-author-localname "author")
(def asp-author (format "%s:%s" cm-prefix asp-author-localname))
(def asp-dublincore-localname "dublincore")
(def asp-dublincore (format "%s:%s" cm-prefix asp-dublincore-localname))
(def asp-basable-localname "basable")
(def asp-basable (format "%s:%s" cm-prefix asp-basable-localname))
(def asp-partable-localname "partable")
(def asp-partable (format "%s:%s" cm-prefix asp-partable-localname))
(def asp-referencing-localname "referencing")
(def asp-referencing (format "%s:%s" cm-prefix asp-referencing-localname))
(def asp-replaceable-localname "replaceable")
(def asp-replaceable (format "%s:%s" cm-prefix asp-replaceable-localname))
(def asp-effectivity-localname "effectivity")
(def asp-effectivity (format "%s:%s" cm-prefix asp-effectivity-localname))
(def asp-summarizable-localname "summarizable")
(def asp-summarizable (format "%s:%s" cm-prefix asp-summarizable-localname))
(def asp-countable-localname "countable")
(def asp-countable (format "%s:%s" cm-prefix asp-countable-localname))
(def asp-copiedfrom-localname "copiedfrom")
(def asp-copiedfrom (format "%s:%s" cm-prefix asp-copiedfrom-localname))
(def asp-workingcopy-localname "workingcopy")
(def asp-workingcopy (format "%s:%s" cm-prefix asp-workingcopy-localname))
(def asp-checked-out-localname "checkedOut")
(def asp-checked-out (format "%s:%s" cm-prefix asp-checked-out-localname))
(def asp-cmis-created-checked-out-localname "cmisCreatedCheckedOut")
(def asp-cmis-created-checked-out (format "%s:%s" cm-prefix asp-cmis-created-checked-out-localname))
(def asp-versionable-localname "versionable")
(def asp-versionable (format "%s:%s" cm-prefix asp-versionable-localname))
(def asp-lockable-localname "lockable")
(def asp-lockable (format "%s:%s" cm-prefix asp-lockable-localname))
(def asp-subscribable-localname "subscribable")
(def asp-subscribable (format "%s:%s" cm-prefix asp-subscribable-localname))
(def asp-classifiable-localname "classifiable")
(def asp-classifiable (format "%s:%s" cm-prefix asp-classifiable-localname))
(def asp-generalclassifiable-localname "generalclassifiable")
(def asp-generalclassifiable (format "%s:%s" cm-prefix asp-generalclassifiable-localname))
(def asp-taggable-localname "taggable")
(def asp-taggable (format "%s:%s" cm-prefix asp-taggable-localname))
(def asp-tagscope-localname "tagscope")
(def asp-tagscope (format "%s:%s" cm-prefix asp-tagscope-localname))
(def asp-rateable-localname "rateable")
(def asp-rateable (format "%s:%s" cm-prefix asp-rateable-localname))
(def asp-likes-rating-scheme-rollups-localname "likesRatingSchemeRollups")
(def asp-likes-rating-scheme-rollups (format "%s:%s" cm-prefix asp-likes-rating-scheme-rollups-localname))
(def asp-five-star-rating-scheme-rollups-localname "fiveStarRatingSchemeRollups")
(def asp-five-star-rating-scheme-rollups (format "%s:%s" cm-prefix asp-five-star-rating-scheme-rollups-localname))
(def asp-attachable-localname "attachable")
(def asp-attachable (format "%s:%s" cm-prefix asp-attachable-localname))
(def asp-emailed-localname "emailed")
(def asp-emailed (format "%s:%s" cm-prefix asp-emailed-localname))
(def asp-referencesnode-localname "referencesnode")
(def asp-referencesnode (format "%s:%s" cm-prefix asp-referencesnode-localname))
(def asp-ml-document-localname "mlDocument")
(def asp-ml-document (format "%s:%s" cm-prefix asp-ml-document-localname))
(def asp-ml-empty-translation-localname "mlEmptyTranslation")
(def asp-ml-empty-translation (format "%s:%s" cm-prefix asp-ml-empty-translation-localname))
(def asp-store-selector-localname "storeSelector")
(def asp-store-selector (format "%s:%s" cm-prefix asp-store-selector-localname))
(def asp-preferences-localname "preferences")
(def asp-preferences (format "%s:%s" cm-prefix asp-preferences-localname))
(def asp-syndication-localname "syndication")
(def asp-syndication (format "%s:%s" cm-prefix asp-syndication-localname))
(def asp-geographic-localname "geographic")
(def asp-geographic (format "%s:%s" cm-prefix asp-geographic-localname))
(def asp-rendition-localname "rendition")
(def asp-rendition (format "%s:%s" rn-prefix asp-rendition-localname))
(def asp-rendition2-localname "rendition2")
(def asp-rendition2 (format "%s:%s" rn-prefix asp-rendition2-localname))
(def asp-hidden-rendition-localname "hiddenRendition")
(def asp-hidden-rendition (format "%s:%s" rn-prefix asp-hidden-rendition-localname))
(def asp-visible-rendition-localname "visibleRendition")
(def asp-visible-rendition (format "%s:%s" rn-prefix asp-visible-rendition-localname))
(def asp-renditioned-localname "renditioned")
(def asp-renditioned (format "%s:%s" rn-prefix asp-renditioned-localname))
(def asp-prevent-renditions-localname "preventRenditions")
(def asp-prevent-renditions (format "%s:%s" rn-prefix asp-prevent-renditions-localname))
(def asp-failed-thumbnail-source-localname "failedThumbnailSource")
(def asp-failed-thumbnail-source (format "%s:%s" cm-prefix asp-failed-thumbnail-source-localname))
(def asp-thumbnail-modification-localname "thumbnailModification")
(def asp-thumbnail-modification (format "%s:%s" cm-prefix asp-thumbnail-modification-localname))
(def asp-exif-localname "exif")
(def asp-exif (format "%s:%s" exif-prefix asp-exif-localname))
(def asp-audio-localname "audio")
(def asp-audio (format "%s:%s" audio-prefix asp-audio-localname))
(def asp-index-control-localname "indexControl")
(def asp-index-control (format "%s:%s" cm-prefix asp-index-control-localname))
(def asp-object-localname "object")
(def asp-object (format "%s:%s" webdav-prefix asp-object-localname))
(def asp-localizable-localname "localizable")
(def asp-localizable (format "%s:%s" cm-prefix asp-localizable-localname))
(def asp-translatable-localname "translatable")
(def asp-translatable (format "%s:%s" cm-prefix asp-translatable-localname))
(def asp-thumbnailed-localname "thumbnailed")
(def asp-thumbnailed (format "%s:%s" cm-prefix asp-thumbnailed-localname))
(def prop-title-localname "title")
(def prop-title (format "%s:%s" cm-prefix prop-title-localname))
(def prop-description-localname "description")
(def prop-description (format "%s:%s" cm-prefix prop-description-localname))
(def prop-created-localname "created")
(def prop-created (format "%s:%s" cm-prefix prop-created-localname))
(def prop-creator-localname "creator")
(def prop-creator (format "%s:%s" cm-prefix prop-creator-localname))
(def prop-modified-localname "modified")
(def prop-modified (format "%s:%s" cm-prefix prop-modified-localname))
(def prop-modifier-localname "modifier")
(def prop-modifier (format "%s:%s" cm-prefix prop-modifier-localname))
(def prop-accessed-localname "accessed")
(def prop-accessed (format "%s:%s" cm-prefix prop-accessed-localname))
(def prop-template-localname "template")
(def prop-template (format "%s:%s" cm-prefix prop-template-localname))
(def prop-webscript-localname "webscript")
(def prop-webscript (format "%s:%s" cm-prefix prop-webscript-localname))
(def prop-summary-webscript-localname "summaryWebscript")
(def prop-summary-webscript (format "%s:%s" cm-prefix prop-summary-webscript-localname))
(def prop-remove-after-localname "removeAfter")
(def prop-remove-after (format "%s:%s" cm-prefix prop-remove-after-localname))
(def prop-owner-localname "owner")
(def prop-owner (format "%s:%s" cm-prefix prop-owner-localname))
(def prop-author-localname "author")
(def prop-author (format "%s:%s" cm-prefix prop-author-localname))
(def prop-publisher-localname "publisher")
(def prop-publisher (format "%s:%s" cm-prefix prop-publisher-localname))
(def prop-contributor-localname "contributor")
(def prop-contributor (format "%s:%s" cm-prefix prop-contributor-localname))
(def prop-type-localname "type")
(def prop-type (format "%s:%s" cm-prefix prop-type-localname))
(def prop-identifier-localname "identifier")
(def prop-identifier (format "%s:%s" cm-prefix prop-identifier-localname))
(def prop-dcsource-localname "dcsource")
(def prop-dcsource (format "%s:%s" cm-prefix prop-dcsource-localname))
(def prop-coverage-localname "coverage")
(def prop-coverage (format "%s:%s" cm-prefix prop-coverage-localname))
(def prop-rights-localname "rights")
(def prop-rights (format "%s:%s" cm-prefix prop-rights-localname))
(def prop-subject-localname "subject")
(def prop-subject (format "%s:%s" cm-prefix prop-subject-localname))
(def prop-from-localname "from")
(def prop-from (format "%s:%s" cm-prefix prop-from-localname))
(def prop-to-localname "to")
(def prop-to (format "%s:%s" cm-prefix prop-to-localname))
(def prop-summary-localname "summary")
(def prop-summary (format "%s:%s" cm-prefix prop-summary-localname))
(def prop-hits-localname "hits")
(def prop-hits (format "%s:%s" cm-prefix prop-hits-localname))
(def prop-counter-localname "counter")
(def prop-counter (format "%s:%s" cm-prefix prop-counter-localname))
(def prop-working-copy-owner-localname "workingCopyOwner")
(def prop-working-copy-owner (format "%s:%s" cm-prefix prop-working-copy-owner-localname))
(def prop-working-copy-mode-localname "workingCopyMode")
(def prop-working-copy-mode (format "%s:%s" cm-prefix prop-working-copy-mode-localname))
(def prop-working-copy-label-localname "workingCopyLabel")
(def prop-working-copy-label (format "%s:%s" cm-prefix prop-working-copy-label-localname))
(def prop-version-label-localname "versionLabel")
(def prop-version-label (format "%s:%s" cm-prefix prop-version-label-localname))
(def prop-version-type-localname "versionType")
(def prop-version-type (format "%s:%s" cm-prefix prop-version-type-localname))
(def prop-initial-version-localname "initialVersion")
(def prop-initial-version (format "%s:%s" cm-prefix prop-initial-version-localname))
(def prop-auto-version-localname "autoVersion")
(def prop-auto-version (format "%s:%s" cm-prefix prop-auto-version-localname))
(def prop-auto-version-on-update-props-localname "autoVersionOnUpdateProps")
(def prop-auto-version-on-update-props (format "%s:%s" cm-prefix prop-auto-version-on-update-props-localname))
(def prop-lock-owner-localname "lockOwner")
(def prop-lock-owner (format "%s:%s" cm-prefix prop-lock-owner-localname))
(def prop-lock-type-localname "lockType")
(def prop-lock-type (format "%s:%s" cm-prefix prop-lock-type-localname))
(def prop-lock-lifetime-localname "lockLifetime")
(def prop-lock-lifetime (format "%s:%s" cm-prefix prop-lock-lifetime-localname))
(def prop-expiry-date-localname "expiryDate")
(def prop-expiry-date (format "%s:%s" cm-prefix prop-expiry-date-localname))
(def prop-lock-is-deep-localname "lockIsDeep")
(def prop-lock-is-deep (format "%s:%s" cm-prefix prop-lock-is-deep-localname))
(def prop-lock-additional-info-localname "lockAdditionalInfo")
(def prop-lock-additional-info (format "%s:%s" cm-prefix prop-lock-additional-info-localname))
(def prop-categories-localname "categories")
(def prop-categories (format "%s:%s" cm-prefix prop-categories-localname))
(def prop-taggable-localname "taggable")
(def prop-taggable (format "%s:%s" cm-prefix prop-taggable-localname))
(def prop-tag-scope-cache-localname "tagScopeCache")
(def prop-tag-scope-cache (format "%s:%s" cm-prefix prop-tag-scope-cache-localname))
(def prop-tag-scope-summary-localname "tagScopeSummary")
(def prop-tag-scope-summary (format "%s:%s" cm-prefix prop-tag-scope-summary-localname))
(def prop-likes-rating-scheme-count-localname "likesRatingSchemeCount")
(def prop-likes-rating-scheme-count (format "%s:%s" cm-prefix prop-likes-rating-scheme-count-localname))
(def prop-likes-rating-scheme-total-localname "likesRatingSchemeTotal")
(def prop-likes-rating-scheme-total (format "%s:%s" cm-prefix prop-likes-rating-scheme-total-localname))
(def prop-five-star-rating-scheme-count-localname "fiveStarRatingSchemeCount")
(def prop-five-star-rating-scheme-count (format "%s:%s" cm-prefix prop-five-star-rating-scheme-count-localname))
(def prop-five-star-rating-scheme-total-localname "fiveStarRatingSchemeTotal")
(def prop-five-star-rating-scheme-total (format "%s:%s" cm-prefix prop-five-star-rating-scheme-total-localname))
(def prop-originator-localname "originator")
(def prop-originator (format "%s:%s" cm-prefix prop-originator-localname))
(def prop-addressee-localname "addressee")
(def prop-addressee (format "%s:%s" cm-prefix prop-addressee-localname))
(def prop-addressees-localname "addressees")
(def prop-addressees (format "%s:%s" cm-prefix prop-addressees-localname))
(def prop-subjectline-localname "subjectline")
(def prop-subjectline (format "%s:%s" cm-prefix prop-subjectline-localname))
(def prop-sentdate-localname "sentdate")
(def prop-sentdate (format "%s:%s" cm-prefix prop-sentdate-localname))
(def prop-noderef-localname "noderef")
(def prop-noderef (format "%s:%s" cm-prefix prop-noderef-localname))
(def prop-store-name-localname "storeName")
(def prop-store-name (format "%s:%s" cm-prefix prop-store-name-localname))
(def prop-preference-values-localname "preferenceValues")
(def prop-preference-values (format "%s:%s" cm-prefix prop-preference-values-localname))
(def prop-published-localname "published")
(def prop-published (format "%s:%s" cm-prefix prop-published-localname))
(def prop-updated-localname "updated")
(def prop-updated (format "%s:%s" cm-prefix prop-updated-localname))
(def prop-latitude-localname "latitude")
(def prop-latitude (format "%s:%s" cm-prefix prop-latitude-localname))
(def prop-longitude-localname "longitude")
(def prop-longitude (format "%s:%s" cm-prefix prop-longitude-localname))
(def prop-content-url-hash-code-localname "contentUrlHashCode")
(def prop-content-url-hash-code (format "%s:%s" rn-prefix prop-content-url-hash-code-localname))
(def prop-last-thumbnail-modification-localname "lastThumbnailModification")
(def prop-last-thumbnail-modification (format "%s:%s" cm-prefix prop-last-thumbnail-modification-localname))
(def prop-date-time-original-localname "dateTimeOriginal")
(def prop-date-time-original (format "%s:%s" exif-prefix prop-date-time-original-localname))
(def prop-pixel-xdimension-localname "pixelXDimension")
(def prop-pixel-xdimension (format "%s:%s" exif-prefix prop-pixel-xdimension-localname))
(def prop-pixel-ydimension-localname "pixelYDimension")
(def prop-pixel-ydimension (format "%s:%s" exif-prefix prop-pixel-ydimension-localname))
(def prop-exposure-time-localname "exposureTime")
(def prop-exposure-time (format "%s:%s" exif-prefix prop-exposure-time-localname))
(def prop-f-number-localname "fNumber")
(def prop-f-number (format "%s:%s" exif-prefix prop-f-number-localname))
(def prop-flash-localname "flash")
(def prop-flash (format "%s:%s" exif-prefix prop-flash-localname))
(def prop-focal-length-localname "focalLength")
(def prop-focal-length (format "%s:%s" exif-prefix prop-focal-length-localname))
(def prop-iso-speed-ratings-localname "isoSpeedRatings")
(def prop-iso-speed-ratings (format "%s:%s" exif-prefix prop-iso-speed-ratings-localname))
(def prop-manufacturer-localname "manufacturer")
(def prop-manufacturer (format "%s:%s" exif-prefix prop-manufacturer-localname))
(def prop-model-localname "model")
(def prop-model (format "%s:%s" exif-prefix prop-model-localname))
(def prop-software-localname "software")
(def prop-software (format "%s:%s" exif-prefix prop-software-localname))
(def prop-orientation-localname "orientation")
(def prop-orientation (format "%s:%s" exif-prefix prop-orientation-localname))
(def prop-x-resolution-localname "xResolution")
(def prop-x-resolution (format "%s:%s" exif-prefix prop-x-resolution-localname))
(def prop-y-resolution-localname "yResolution")
(def prop-y-resolution (format "%s:%s" exif-prefix prop-y-resolution-localname))
(def prop-resolution-unit-localname "resolutionUnit")
(def prop-resolution-unit (format "%s:%s" exif-prefix prop-resolution-unit-localname))
(def prop-album-localname "album")
(def prop-album (format "%s:%s" audio-prefix prop-album-localname))
(def prop-artist-localname "artist")
(def prop-artist (format "%s:%s" audio-prefix prop-artist-localname))
(def prop-composer-localname "composer")
(def prop-composer (format "%s:%s" audio-prefix prop-composer-localname))
(def prop-engineer-localname "engineer")
(def prop-engineer (format "%s:%s" audio-prefix prop-engineer-localname))
(def prop-genre-localname "genre")
(def prop-genre (format "%s:%s" audio-prefix prop-genre-localname))
(def prop-track-number-localname "trackNumber")
(def prop-track-number (format "%s:%s" audio-prefix prop-track-number-localname))
(def prop-release-date-localname "releaseDate")
(def prop-release-date (format "%s:%s" audio-prefix prop-release-date-localname))
(def prop-sample-rate-localname "sampleRate")
(def prop-sample-rate (format "%s:%s" audio-prefix prop-sample-rate-localname))
(def prop-sample-type-localname "sampleType")
(def prop-sample-type (format "%s:%s" audio-prefix prop-sample-type-localname))
(def prop-channel-type-localname "channelType")
(def prop-channel-type (format "%s:%s" audio-prefix prop-channel-type-localname))
(def prop-compressor-localname "compressor")
(def prop-compressor (format "%s:%s" audio-prefix prop-compressor-localname))
(def prop-is-indexed-localname "isIndexed")
(def prop-is-indexed (format "%s:%s" cm-prefix prop-is-indexed-localname))
(def prop-is-content-indexed-localname "isContentIndexed")
(def prop-is-content-indexed (format "%s:%s" cm-prefix prop-is-content-indexed-localname))
(def prop-deadproperties-localname "deadproperties")
(def prop-deadproperties (format "%s:%s" webdav-prefix prop-deadproperties-localname))
(def prop-locale-localname "locale")
(def prop-locale (format "%s:%s" cm-prefix prop-locale-localname))
(def prop-automatic-update-localname "automaticUpdate")
(def prop-automatic-update (format "%s:%s" cm-prefix prop-automatic-update-localname))
(def prop-name-localname "name")
(def prop-name (format "%s:%s" cm-prefix prop-name-localname))
(def prop-content-localname "content")
(def prop-content (format "%s:%s" cm-prefix prop-content-localname))
(def prop-model-name-localname "modelName")
(def prop-model-name (format "%s:%s" cm-prefix prop-model-name-localname))
(def prop-model-description-localname "modelDescription")
(def prop-model-description (format "%s:%s" cm-prefix prop-model-description-localname))
(def prop-model-author-localname "modelAuthor")
(def prop-model-author (format "%s:%s" cm-prefix prop-model-author-localname))
(def prop-model-published-date-localname "modelPublishedDate")
(def prop-model-published-date (format "%s:%s" cm-prefix prop-model-published-date-localname))
(def prop-model-version-localname "modelVersion")
(def prop-model-version (format "%s:%s" cm-prefix prop-model-version-localname))
(def prop-model-active-localname "modelActive")
(def prop-model-active (format "%s:%s" cm-prefix prop-model-active-localname))
(def prop-destination-localname "destination")
(def prop-destination (format "%s:%s" cm-prefix prop-destination-localname))
(def prop-user-name-localname "userName")
(def prop-user-name (format "%s:%s" cm-prefix prop-user-name-localname))
(def prop-home-folder-localname "homeFolder")
(def prop-home-folder (format "%s:%s" cm-prefix prop-home-folder-localname))
(def prop-first-name-localname "firstName")
(def prop-first-name (format "%s:%s" cm-prefix prop-first-name-localname))
(def prop-last-name-localname "lastName")
(def prop-last-name (format "%s:%s" cm-prefix prop-last-name-localname))
(def prop-middle-name-localname "middleName")
(def prop-middle-name (format "%s:%s" cm-prefix prop-middle-name-localname))
(def prop-email-localname "email")
(def prop-email (format "%s:%s" cm-prefix prop-email-localname))
(def prop-organization-id-localname "organizationId")
(def prop-organization-id (format "%s:%s" cm-prefix prop-organization-id-localname))
(def prop-home-folder-provider-localname "homeFolderProvider")
(def prop-home-folder-provider (format "%s:%s" cm-prefix prop-home-folder-provider-localname))
(def prop-default-home-folder-path-localname "defaultHomeFolderPath")
(def prop-default-home-folder-path (format "%s:%s" cm-prefix prop-default-home-folder-path-localname))
(def prop-presence-provider-localname "presenceProvider")
(def prop-presence-provider (format "%s:%s" cm-prefix prop-presence-provider-localname))
(def prop-presence-username-localname "presenceUsername")
(def prop-presence-username (format "%s:%s" cm-prefix prop-presence-username-localname))
(def prop-organization-localname "organization")
(def prop-organization (format "%s:%s" cm-prefix prop-organization-localname))
(def prop-jobtitle-localname "jobtitle")
(def prop-jobtitle (format "%s:%s" cm-prefix prop-jobtitle-localname))
(def prop-location-localname "location")
(def prop-location (format "%s:%s" cm-prefix prop-location-localname))
(def prop-persondescription-localname "persondescription")
(def prop-persondescription (format "%s:%s" cm-prefix prop-persondescription-localname))
(def prop-telephone-localname "telephone")
(def prop-telephone (format "%s:%s" cm-prefix prop-telephone-localname))
(def prop-mobile-localname "mobile")
(def prop-mobile (format "%s:%s" cm-prefix prop-mobile-localname))
(def prop-companyaddress1-localname "companyaddress1")
(def prop-companyaddress1 (format "%s:%s" cm-prefix prop-companyaddress1-localname))
(def prop-companyaddress2-localname "companyaddress2")
(def prop-companyaddress2 (format "%s:%s" cm-prefix prop-companyaddress2-localname))
(def prop-companyaddress3-localname "companyaddress3")
(def prop-companyaddress3 (format "%s:%s" cm-prefix prop-companyaddress3-localname))
(def prop-companypostcode-localname "companypostcode")
(def prop-companypostcode (format "%s:%s" cm-prefix prop-companypostcode-localname))
(def prop-companytelephone-localname "companytelephone")
(def prop-companytelephone (format "%s:%s" cm-prefix prop-companytelephone-localname))
(def prop-companyfax-localname "companyfax")
(def prop-companyfax (format "%s:%s" cm-prefix prop-companyfax-localname))
(def prop-companyemail-localname "companyemail")
(def prop-companyemail (format "%s:%s" cm-prefix prop-companyemail-localname))
(def prop-skype-localname "skype")
(def prop-skype (format "%s:%s" cm-prefix prop-skype-localname))
(def prop-instantmsg-localname "instantmsg")
(def prop-instantmsg (format "%s:%s" cm-prefix prop-instantmsg-localname))
(def prop-user-status-localname "userStatus")
(def prop-user-status (format "%s:%s" cm-prefix prop-user-status-localname))
(def prop-user-status-time-localname "userStatusTime")
(def prop-user-status-time (format "%s:%s" cm-prefix prop-user-status-time-localname))
(def prop-googleusername-localname "googleusername")
(def prop-googleusername (format "%s:%s" cm-prefix prop-googleusername-localname))
(def prop-email-feed-disabled-localname "emailFeedDisabled")
(def prop-email-feed-disabled (format "%s:%s" cm-prefix prop-email-feed-disabled-localname))
(def prop-subscriptions-private-localname "subscriptionsPrivate")
(def prop-subscriptions-private (format "%s:%s" cm-prefix prop-subscriptions-private-localname))
(def prop-email-feed-id-localname "emailFeedId")
(def prop-email-feed-id (format "%s:%s" cm-prefix prop-email-feed-id-localname))
(def prop-size-current-localname "sizeCurrent")
(def prop-size-current (format "%s:%s" cm-prefix prop-size-current-localname))
(def prop-size-quota-localname "sizeQuota")
(def prop-size-quota (format "%s:%s" cm-prefix prop-size-quota-localname))
(def prop-authority-name-localname "authorityName")
(def prop-authority-name (format "%s:%s" cm-prefix prop-authority-name-localname))
(def prop-authority-display-name-localname "authorityDisplayName")
(def prop-authority-display-name (format "%s:%s" cm-prefix prop-authority-display-name-localname))
(def prop-rating-score-localname "ratingScore")
(def prop-rating-score (format "%s:%s" cm-prefix prop-rating-score-localname))
(def prop-rating-scheme-localname "ratingScheme")
(def prop-rating-scheme (format "%s:%s" cm-prefix prop-rating-scheme-localname))
(def prop-rated-at-localname "ratedAt")
(def prop-rated-at (format "%s:%s" cm-prefix prop-rated-at-localname))
(def prop-failure-count-localname "failureCount")
(def prop-failure-count (format "%s:%s" cm-prefix prop-failure-count-localname))
(def prop-failed-thumbnail-time-localname "failedThumbnailTime")
(def prop-failed-thumbnail-time (format "%s:%s" cm-prefix prop-failed-thumbnail-time-localname))
(def prop-thumbnail-name-localname "thumbnailName")
(def prop-thumbnail-name (format "%s:%s" cm-prefix prop-thumbnail-name-localname))
(def prop-content-property-name-localname "contentPropertyName")
(def prop-content-property-name (format "%s:%s" cm-prefix prop-content-property-name-localname))